import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, basename, extname, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { imageSize } from 'image-size';

const __dirname = dirname(fileURLToPath(import.meta.url));
const galleryDir = join(__dirname, '..', 'public', 'images', 'gallery');
const outFile = join(__dirname, '..', 'src', 'app', 'pages', 'home', 'gallery', 'gallery.config.ts');
const altOverridesFile = join(galleryDir, 'alt.json');

const exts = new Set(['.jpg', '.jpeg', '.png', '.webp']);

const altOverrides = existsSync(altOverridesFile)
  ? JSON.parse(readFileSync(altOverridesFile, 'utf8'))
  : {};

function humanize(name) {
  return name
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

const files = readdirSync(galleryDir)
  .filter((f) => exts.has(extname(f).toLowerCase()))
  .sort();

const items = files.map((file) => {
  const full = join(galleryDir, file);
  const dims = imageSize(readFileSync(full));
  const baseName = basename(file, extname(file));
  const alt = altOverrides[file] ?? humanize(baseName);
  return {
    src: `/images/gallery/${file}`,
    alt,
    width: dims.width,
    height: dims.height,
  };
});

const ts = `// Auto-generated by scripts/generate-gallery.mjs. Do not edit manually.
// To override an alt text, add an entry in public/images/gallery/alt.json:
//   { "drapeau-breton.jpg": "Drapeau breton, weekend de juillet 2024" }

export interface GalleryItem {
  src: string;
  alt: string;
  width: number;
  height: number;
}

export const GALLERY_ITEMS: GalleryItem[] = ${JSON.stringify(items, null, 2)};
`;

writeFileSync(outFile, ts);
console.log(`✓ Generated gallery config with ${items.length} items.`);
