import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { join, basename, extname, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __dirname = dirname(fileURLToPath(import.meta.url));
const galleryDir = join(__dirname, '..', 'public', 'images', 'gallery');
const outFile = join(__dirname, '..', 'src', 'app', 'pages', 'home', 'gallery', 'gallery.config.ts');
const altOverridesFile = join(galleryDir, 'alt.json');

const sourceExts = new Set(['.jpg', '.jpeg', '.png']);
const WEBP_QUALITY = 75;
const MAX_DIMENSION = 1600;

const altOverrides = existsSync(altOverridesFile)
  ? JSON.parse(readFileSync(altOverridesFile, 'utf8'))
  : {};

function humanize(name) {
  return name
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

function isUpToDate(srcPath, webpPath) {
  if (!existsSync(webpPath)) return false;
  return statSync(webpPath).mtimeMs >= statSync(srcPath).mtimeMs;
}

const files = readdirSync(galleryDir)
  .filter((f) => sourceExts.has(extname(f).toLowerCase()))
  .sort();

const items = await Promise.all(
  files.map(async (file) => {
    const srcPath = join(galleryDir, file);
    const webpName = `${basename(file, extname(file))}.webp`;
    const webpPath = join(galleryDir, webpName);

    if (!isUpToDate(srcPath, webpPath)) {
      await sharp(srcPath)
        .resize({ width: MAX_DIMENSION, height: MAX_DIMENSION, fit: 'inside', withoutEnlargement: true })
        .webp({ quality: WEBP_QUALITY })
        .toFile(webpPath);
    }

    const meta = await sharp(webpPath).metadata();
    const alt = altOverrides[file] ?? humanize(basename(file, extname(file)));

    return {
      src: `/images/gallery/${webpName}`,
      alt,
      width: meta.width,
      height: meta.height,
    };
  }),
);

const ts = `// Auto-generated by scripts/generate-gallery.mjs. Do not edit manually.
// To override an alt text, add an entry in public/images/gallery/alt.json:
//   { "drapeau-breton.jpg": "Drapeau breton, weekend de juillet 2024" }

export interface GalleryItem {
  src: string;
  alt: string;
  width: number;
  height: number;
}

export const GALLERY_ITEMS: GalleryItem[] = ${JSON.stringify(items, null, 2)};
`;

writeFileSync(outFile, ts);
console.log(`✓ Generated gallery config with ${items.length} items.`);
